services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize 
      -wait tcp://postgres:5432 -timeout 10s
      pnpm run dev
    ports:
      - ${NEXTJS_PORT}:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/bdd
    env_file:
      - .env
  
  postgres:
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - ./bdd:/var/lib/postgresql/data
    env_file:
      - .env
  
  adminer:
    image: adminer:latest
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
